//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavyClient.RoutingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoutingService.IRoutingWS")]
    public interface IRoutingWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingWS/GetItinerarys", ReplyAction="http://tempuri.org/IRoutingWS/GetItinerarysResponse")]
        string GetItinerarys(string departPoint, string arrivePoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingWS/GetItinerarys", ReplyAction="http://tempuri.org/IRoutingWS/GetItinerarysResponse")]
        System.Threading.Tasks.Task<string> GetItinerarysAsync(string departPoint, string arrivePoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingWS/GetUtils", ReplyAction="http://tempuri.org/IRoutingWS/GetUtilsResponse")]
        string[] GetUtils();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingWS/GetUtils", ReplyAction="http://tempuri.org/IRoutingWS/GetUtilsResponse")]
        System.Threading.Tasks.Task<string[]> GetUtilsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoutingWSChannel : HeavyClient.RoutingService.IRoutingWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoutingWSClient : System.ServiceModel.ClientBase<HeavyClient.RoutingService.IRoutingWS>, HeavyClient.RoutingService.IRoutingWS {
        
        public RoutingWSClient() {
        }
        
        public RoutingWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutingWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetItinerarys(string departPoint, string arrivePoint) {
            return base.Channel.GetItinerarys(departPoint, arrivePoint);
        }
        
        public System.Threading.Tasks.Task<string> GetItinerarysAsync(string departPoint, string arrivePoint) {
            return base.Channel.GetItinerarysAsync(departPoint, arrivePoint);
        }
        
        public string[] GetUtils() {
            return base.Channel.GetUtils();
        }
        
        public System.Threading.Tasks.Task<string[]> GetUtilsAsync() {
            return base.Channel.GetUtilsAsync();
        }
    }
}
